name: docs

on:
  push:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Build and publish docs
        uses: TinyTapeout/tt-gds-action/docs@ttsky26c
